# ============================================================================
#  SHIPPED PREFERENCE DEFAULTS
#
#  This file holds taste, and nothing else. A colour scheme, a leader key, how
#  wide the agent pane is. None of it is architecture: change any value here
#  and the workstation still works exactly the same way, it just looks or feels
#  different.
#
#  The architecture — what must exist, where it is linked, which paths this
#  repository is allowed to write to — lives in DeclaredState.psd1. Keeping the
#  two apart is what lets a future `macss workstation` ship an opinionated
#  default without shipping one person's opinion as if it were a contract.
#  See docs/adr/0005-architecture-and-preference-are-different-things.md
#
#  ----------------------------------------------------------------------------
#  HOW TO OVERRIDE
#
#  Do not edit this file to change your own machine. Write only the keys you
#  want to change into a file of your own:
#
#      Windows   %LOCALAPPDATA%\workstation.preferences.psd1
#      Linux     $XDG_CONFIG_HOME/workstation.preferences.psd1
#
#  For example, to change nothing but the colours:
#
#      @{ Terminal = @{ ColorScheme = 'Catppuccin Mocha' }
#         Editor   = @{ ColorScheme = 'catppuccin' } }
#
#  Values are merged section by section, so anything you leave out keeps the
#  default below. `Install-Workstation -Plan` shows the resolved result, and
#  `Get-WorkstationPreference -ShowSources` shows which file each value came
#  from.
# ============================================================================

@{

    # Schema version of this file. Bumped when a key is renamed or removed, so
    # a future resolver can migrate an override written against an older shape.
    Schema = 1


    # ------------------------------------------------------------------------
    #  Workstation behaviour
    # ------------------------------------------------------------------------
    Workstation = @{

        # Which agent Start-Workstation opens when none is named.
        # Must be one of the agents declared in DeclaredState.psd1.
        DefaultAgent = 'claude'
    }


    # ------------------------------------------------------------------------
    #  Layout proportions
    #
    #  The three-pane shape itself is architecture and is not configurable here.
    #  How much room each pane gets is taste.
    # ------------------------------------------------------------------------
    Layout = @{

        # Fraction of the window width taken by the agent pane, on the right.
        AgentPaneWidth = 0.38

        # Fraction of the left column taken by the shell pane, at the bottom.
        TerminalPaneHeight = 0.22

        # Maximise the window on open.
        MaximizeOnStart = $true

        # Dim the pane that does not have focus, so it is obvious where the
        # cursor is.
        DimInactivePanes = $true
    }


    # ------------------------------------------------------------------------
    #  Terminal appearance (WezTerm)
    # ------------------------------------------------------------------------
    Terminal = @{

        # Any scheme name WezTerm knows. `wezterm ls-fonts --list-system` and
        # the WezTerm colour scheme gallery list the options.
        ColorScheme = 'Tokyo Night'

        # JetBrains Mono ships inside WezTerm, so it needs no installation.
        FontFamily = 'JetBrains Mono'
        FontSize   = 11.0
        LineHeight = 1.1

        WindowPadding   = 8
        ScrollbackLines = 10000
    }


    # ------------------------------------------------------------------------
    #  Editor appearance and behaviour (Neovim)
    # ------------------------------------------------------------------------
    Editor = @{

        # Must match a colour scheme one of the installed plugins provides.
        ColorScheme = 'tokyonight-night'

        # The leader key. A single space is the common choice.
        LeaderKey = ' '

        RelativeNumber = $false
        TabWidth       = 2

        FileTreeWidth       = 34
        FileTreePosition    = 'left'
        OpenFileTreeOnStart = $true
    }
}
